### ISSUE TITLE
Dataset repository is unaccessible

### ISSUE THREAD

**Issue by peppocola** [nlbse2023/nlbse2023.github.io#3]
The link which should include the datasets, rules and baselines is not accessible (error 404).

Link : https://github.com/nlbse2023/issue-classification

**Comment by rafaelkallis** [comment]
Hi @peppocola we will be live very soon ;)

**Comment by peppocola** [comment]
@rafaelkallis thank you :D

**Comment by rafaelkallis** [comment]
@peppocola we are live now https://github.com/nlbse2023/issue-report-classification !
